using Corprio.SocialWorker.Models;
using System.Collections.Generic;

namespace Corprio.SocialWorker.Dictionaries
{
    public class BabelFish
    {
        public static readonly Dictionary<string, Dictionary<BotLanguage, string>> Vocab = new()
        {
            ["AskProduct"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "If you want to purchase a product, please input its name or product code, or visit the relevant catalogue. ",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
            ["AskOneProduct"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "Do you want to buy {0}? Please answer in YES or NO. ",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
            ["AskMultiProducts"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "Are you interested the following products? If yes, input the number next to product name.\n{0}",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
            ["AskProductVariation"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "Which \'{0}\'? Please input the number next to each choice.\n{1}",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
            ["NoneOfTheAbove"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "0 - None of the above. ",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
            ["CannotFindProduct"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "I couldn't find a product that matches your input \'{0}\'. If you are want to purchase a product, please input its name or product code, or visit the relevant catalogue. ",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
            ["Err_NotUnderstand"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "I don't understand the input. ",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },            
            ["AskQty"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "How many units of {0} do you want to buy? ",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
            ["Err_DefaultMsg"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "Error in the chatbot. Please visit the relevant catalogue if you wish to make a purchase. Sorry for any inconvenience caused. ",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
            ["Err_ProductNotFound"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "Sorry, that product no longer exists. ",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
            ["Hint_GenByBot"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "(Note: This message is generated by a bot.) ",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
            ["Hint_Cancel"] = new Dictionary<BotLanguage, string>()
            {
                [BotLanguage.English] = "(Note: You can input '!c' to cancel the current operation.) ",
                [BotLanguage.TraditionalChinese] = "",
                [BotLanguage.SimplifiedChinese] = "",
            },
        };

        public static readonly Dictionary<string, int> Numbers = new Dictionary<string, int>();

        public static readonly Dictionary<string, int> YesNo = new()
        {
            ["是"] = 1,            
            ["yes"] = 1,
            ["y"] = 1,
            ["yup"] = 1,
            ["yea"] = 1,
            ["yeah"] = 1,
            ["sure"] = 1,            
            ["oui"] = 1,
            ["不是"] = 2,
            ["no"] = 2,
            ["n"] = 2,
            ["nope"] = 2,
            ["non"] = 2,
        };

        public const string KillCode = "!c";
    }
}
