//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corprio.SocialWorker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corprio.SocialWorker.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        public static string AddLine {
            get {
                return ResourceManager.GetString("AddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corprio Sales Master is a free application software for managing your sales transactions such as orders and invoices.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your sales &lt;br&gt; easily and accurately.
        /// </summary>
        public static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill sales order.
        /// </summary>
        public static string BillSalesOrder {
            get {
                return ResourceManager.GetString("BillSalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create invoice.
        /// </summary>
        public static string btnCreateInvoice {
            get {
                return ResourceManager.GetString("btnCreateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The catalogue was successfully published to your social media..
        /// </summary>
        public static string CataloguePublicationCompletedMessage {
            get {
                return ResourceManager.GetString("CataloguePublicationCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning an invoice will create a sales return record and invoiced products will be returned to warehouse automatically.  Are you sure to proceed returning this invoice?.
        /// </summary>
        public static string ConfirmReturnInvoice {
            get {
                return ResourceManager.GetString("ConfirmReturnInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to void this invoice?.
        /// </summary>
        public static string ConfirmVoidInvoice {
            get {
                return ResourceManager.GetString("ConfirmVoidInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to void this sales order?.
        /// </summary>
        public static string ConfirmVoidOrder {
            get {
                return ResourceManager.GetString("ConfirmVoidOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to void this sales return?.
        /// </summary>
        public static string ConfirmVoidSalesReturn {
            get {
                return ResourceManager.GetString("ConfirmVoidSalesReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Facebook.
        /// </summary>
        public static string ConnectFacebook {
            get {
                return ResourceManager.GetString("ConnectFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit amount.
        /// </summary>
        public static string DepositAmount {
            get {
                return ResourceManager.GetString("DepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount %.
        /// </summary>
        public static string DiscountPercent {
            get {
                return ResourceManager.GetString("DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts.
        /// </summary>
        public static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can manage your orders from customers easily and then process orders, issue and print invoices for your daily operations with minimal faults..
        /// </summary>
        public static string Feature1Description {
            get {
                return ResourceManager.GetString("Feature1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Sales Operations.
        /// </summary>
        public static string Feature1Title {
            get {
                return ResourceManager.GetString("Feature1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can simply use the prebuilt report templates or you can add your own fields and adjust the layout with a user-friendly report builder, based on your company’s needs..
        /// </summary>
        public static string Feature2Description {
            get {
                return ResourceManager.GetString("Feature2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-customizable Report Format.
        /// </summary>
        public static string Feature2Title {
            get {
                return ResourceManager.GetString("Feature2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free to Use.
        /// </summary>
        public static string Free_to_Use {
            get {
                return ResourceManager.GetString("Free to Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be charged for using this app forever. Join Corprio now to get started..
        /// </summary>
        public static string FreeToUseDescription {
            get {
                return ResourceManager.GetString("FreeToUseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_page {
            get {
                return ResourceManager.GetString("Home page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice amount.
        /// </summary>
        public static string InvoiceAmount {
            get {
                return ResourceManager.GetString("InvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Bot.
        /// </summary>
        public static string InvoiceBot {
            get {
                return ResourceManager.GetString("InvoiceBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string InvoiceCount {
            get {
                return ResourceManager.GetString("InvoiceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices are the confirmed sales of your business. You can search and print the invoices here..
        /// </summary>
        public static string InvoiceDescription {
            get {
                return ResourceManager.GetString("InvoiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform the required action because the invoice has been voided..
        /// </summary>
        public static string InvoiceHasBeenVoided {
            get {
                return ResourceManager.GetString("InvoiceHasBeenVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inv No..
        /// </summary>
        public static string InvoiceNum {
            get {
                return ResourceManager.GetString("InvoiceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report ID for invoice printout.
        /// </summary>
        public static string InvoicePrintReportID {
            get {
                return ResourceManager.GetString("InvoicePrintReportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the report layout used for printing invoices.
        /// </summary>
        public static string InvoicePrintReportID_Description {
            get {
                return ResourceManager.GetString("InvoicePrintReportID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change this unless you have created your own invoice layout.
        /// </summary>
        public static string InvoicePrintReportID_Warning {
            get {
                return ResourceManager.GetString("InvoicePrintReportID_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Summary.
        /// </summary>
        public static string InvoiceSummary {
            get {
                return ResourceManager.GetString("InvoiceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        public static string IsInvoiceReturned {
            get {
                return ResourceManager.GetString("IsInvoiceReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join for FREE!.
        /// </summary>
        public static string Join_for_FREE_ {
            get {
                return ResourceManager.GetString("Join for FREE!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price currency.
        /// </summary>
        public static string ListPriceCurrency {
            get {
                return ResourceManager.GetString("ListPriceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Price Value.
        /// </summary>
        public static string ListPriceValue {
            get {
                return ResourceManager.GetString("ListPriceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More apps from Corprio....
        /// </summary>
        public static string More_apps_from_Corprio___ {
            get {
                return ResourceManager.GetString("More apps from Corprio...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the organization owner can make changes.
        /// </summary>
        public static string MsgForOwnerOnly {
            get {
                return ResourceManager.GetString("MsgForOwnerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice is fully paid!.
        /// </summary>
        public static string MsgInvoiceFullyPaid {
            get {
                return ResourceManager.GetString("MsgInvoiceFullyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice has been voided!.
        /// </summary>
        public static string MsgInvoiceIsVoided {
            get {
                return ResourceManager.GetString("MsgInvoiceIsVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have the &quot;Approve&quot; permission..
        /// </summary>
        public static string MsgNoApprovePermission {
            get {
                return ResourceManager.GetString("MsgNoApprovePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order is fully paid!.
        /// </summary>
        public static string MsgSalesOrderFullyPaid {
            get {
                return ResourceManager.GetString("MsgSalesOrderFullyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order has been voided!.
        /// </summary>
        public static string MsgSalesOrderIsVoided {
            get {
                return ResourceManager.GetString("MsgSalesOrderIsVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sales order has been voided already!  It cannot be voided again..
        /// </summary>
        public static string OrderHasBeenVoided {
            get {
                return ResourceManager.GetString("OrderHasBeenVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Link.
        /// </summary>
        public static string PaymentLink {
            get {
                return ResourceManager.GetString("PaymentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment link has been copied to the clipboard!.
        /// </summary>
        public static string PaymentLinkCopied {
            get {
                return ResourceManager.GetString("PaymentLinkCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can share this hyperlink with your customer for making online payment..
        /// </summary>
        public static string PaymentLinkDesc {
            get {
                return ResourceManager.GetString("PaymentLinkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend 480px X 480px png or jpg file.
        /// </summary>
        public static string ProductImageSpec {
            get {
                return ResourceManager.GetString("ProductImageSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product was successfully published to your social media..
        /// </summary>
        public static string ProductPublicationCompletedMessage {
            get {
                return ResourceManager.GetString("ProductPublicationCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to unapprove this record?.
        /// </summary>
        public static string PromptUnapprove {
            get {
                return ResourceManager.GetString("PromptUnapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication completed.
        /// </summary>
        public static string PublicationCompletedTitle {
            get {
                return ResourceManager.GetString("PublicationCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Catalogue.
        /// </summary>
        public static string PublishCatalogue {
            get {
                return ResourceManager.GetString("PublishCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish a post to Facebook and Instagram.
        /// </summary>
        public static string PublishCatalogueHint {
            get {
                return ResourceManager.GetString("PublishCatalogueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to publish this catalogue? A post will be made to your Facebook page(s) and Instagram account(s)..
        /// </summary>
        public static string PublishCataloguePrompt {
            get {
                return ResourceManager.GetString("PublishCataloguePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Product.
        /// </summary>
        public static string PublishProduct {
            get {
                return ResourceManager.GetString("PublishProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish a post to Facebook and Instagram.
        /// </summary>
        public static string PublishProductHint {
            get {
                return ResourceManager.GetString("PublishProductHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to publish this product? A post will be made to your Facebook page(s) and Instagram account(s)..
        /// </summary>
        public static string PublishProductPrompt {
            get {
                return ResourceManager.GetString("PublishProductPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Invoices.
        /// </summary>
        public static string Recent_invoices {
            get {
                return ResourceManager.GetString("Recent invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Orders.
        /// </summary>
        public static string Recent_Orders {
            get {
                return ResourceManager.GetString("Recent Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales return.
        /// </summary>
        public static string ReturnInvoice {
            get {
                return ResourceManager.GetString("ReturnInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Dashboard.
        /// </summary>
        public static string Sales_Dashboard {
            get {
                return ResourceManager.GetString("Sales Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Location.
        /// </summary>
        public static string Sales_Location {
            get {
                return ResourceManager.GetString("Sales Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Rep.
        /// </summary>
        public static string Sales_Rep {
            get {
                return ResourceManager.GetString("Sales Rep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales locations are the places where the transactions are taken place. A physical shop is a good example of a sales location..
        /// </summary>
        public static string SalesLocationDescription {
            get {
                return ResourceManager.GetString("SalesLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order.
        /// </summary>
        public static string SalesOrder {
            get {
                return ResourceManager.GetString("SalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order Bot.
        /// </summary>
        public static string SalesOrderBot {
            get {
                return ResourceManager.GetString("SalesOrderBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales orders are the buying requests from customers. You should bill your sales orders into invoices when they are delivered or picked up..
        /// </summary>
        public static string SalesOrderDescription {
            get {
                return ResourceManager.GetString("SalesOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO No..
        /// </summary>
        public static string SalesOrderNum {
            get {
                return ResourceManager.GetString("SalesOrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report ID for sales order printout.
        /// </summary>
        public static string SalesOrderPrintReportID {
            get {
                return ResourceManager.GetString("SalesOrderPrintReportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the report layout used for printing sales orders.
        /// </summary>
        public static string SalesOrderPrintReportID_Description {
            get {
                return ResourceManager.GetString("SalesOrderPrintReportID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change this unless you have created your own sales order layout.
        /// </summary>
        public static string SalesOrderPrintReportID_Warning {
            get {
                return ResourceManager.GetString("SalesOrderPrintReportID_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order Summary.
        /// </summary>
        public static string SalesOrderSummary {
            get {
                return ResourceManager.GetString("SalesOrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales reps (sales representatives) are the sales persons who take the order or invoice in charge. When you want to trace an order or calculate commission for a staff, sales rep is helpful for you..
        /// </summary>
        public static string SalesRepDescription {
            get {
                return ResourceManager.GetString("SalesRepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Return.
        /// </summary>
        public static string SalesReturn {
            get {
                return ResourceManager.GetString("SalesReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales return are records where customers return purchased goods or services..
        /// </summary>
        public static string SalesReturnDescription {
            get {
                return ResourceManager.GetString("SalesReturnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sales return has been voided already!  It cannot be voided again..
        /// </summary>
        public static string SalesReturnHasBeenVoided {
            get {
                return ResourceManager.GetString("SalesReturnHasBeenVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input invoice number, sales order number, customer name, phone, product code or name to search.
        /// </summary>
        public static string SearchInvoiceTips {
            get {
                return ResourceManager.GetString("SearchInvoiceTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input sales order number, customer name, phone, product code or name to search.
        /// </summary>
        public static string SearchOrderTips {
            get {
                return ResourceManager.GetString("SearchOrderTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input sales return number. invoice number, customer name, phone, product code or name to search.
        /// </summary>
        public static string SearchReturnTips {
            get {
                return ResourceManager.GetString("SearchReturnTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse for deducting stock.
        /// </summary>
        public static string SOWarehouseDesc {
            get {
                return ResourceManager.GetString("SOWarehouseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-total.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template was saved..
        /// </summary>
        public static string TemplateSavedMessage {
            get {
                return ResourceManager.GetString("TemplateSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template saved.
        /// </summary>
        public static string TemplateSavedTitle {
            get {
                return ResourceManager.GetString("TemplateSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Qty.
        /// </summary>
        public static string TotalQty {
            get {
                return ResourceManager.GetString("TotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapprove.
        /// </summary>
        public static string Unapprove {
            get {
                return ResourceManager.GetString("Unapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measure.
        /// </summary>
        public static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
    }
}
