export enum MessageType {
    CataloguePost = 'CataloguePost',
    ProductPost = 'ProductPost'
}

export enum Selector {
    addComponentButton_Catalogue = '#component-btn-catalogue',
    addCustomTextButton_Catalogue = '#custom-btn-catalogue',
    addComponentButton_Product = '#component-btn-product',
    addCustomTextButton_Product = '#custom-btn-product',
    blockPanel_Catalogue = '#block-panel-catalogue',
    blockPanel_Catalogue_RemoveButton_Last = '#block-panel-catalogue .remove-btn:last',
    blockPanel_Catalogue_Input_Last = '#block-panel-catalogue .custom-block:last',
    blockPanel_Catalogue_DragBlock_Last = '#block-panel-catalogue .drag-block:last',
    blockPanel_Product = '#block-panel-product',
    blockPanel_Product_RemoveButton_Last = '#block-panel-product .remove-btn:last',
    blockPanel_Product_Input_Last = '#block-panel-product .custom-block:last',
    blockPanel_Product_DragBlock_Last = '#block-panel-product .drag-block:last',
    catalogueSetting = '#catalogue-setting',
    componentSelect_Catalogue = '#component-select-catalogue',
    componentSelect_Product = '#component-select-product',
    customTextInput_Catalogue = '#custom-input-catalogue',
    customTextInput_Product = '#custom-input-product',
    fbDialogue = '#fb-dialogue',
    fbDialogue2 = '#fb-dialogue2',
    keywordInput_Product = '#keyword-input-product',
    loadIndicator_Top = '#load-indicator-top',
    loginButton = '#loginBtn',
    logoutButton = '#logoutBtn',
    previewPanel_Catalogue = '#preview-panel-catalogue',
    previewPanel_Product = '#preview-panel-product',
    restoreDefaultButton_Catalogue = '#restore-default-btn-catalogue',
    restoreDefaultButton_Product = '#restore-default-btn-product',
    saveSettingButtons = '.save-setting-btn',
    saveTemplateButton_Catalogue = '#save-template-btn-catalogue',
    saveTemplateButton_Product = '#save-template-btn-product',
}